on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

name: gefs_osn_stage3

jobs:
  docker:
    runs-on: ubuntu-latest #self-hosted
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    permissions:
     contents: write
    container: rocker/geospatial:latest
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: YARR-forecast


      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_github("eco4cast/gefs4cast")
          remotes::install_github("cboettig/duckdbfs")
          install.packages("minioclient")
          install.packages("decor")
          install.packages("imputeTS")
          install.packages("future")
          install.packages("furrr")
          remotes::install_version("arrow", version = "20.0.0")
          
      - name: Download Pseudo
        shell: Rscript {0}
        run: source("YARR-forecast/drivers/download_psuedo.R")

      - name: Update Stage3
        shell: Rscript {0}
        run: source("YARR-forecast/drivers/update_stage3.R")

      #- name: Healthcheck
      #  run: curl -m 10 --retry 5 https://hc-ping.com/6c3dec04-631a-4a8e-8c55-8837f2827e07
