on:
  # schedule:
  #   - cron: '0 5 * * *'
  workflow_dispatch:


name: targets

jobs:
  generate_targets:
    runs-on: ubuntu-latest #[self-hosted]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.MW_ACCESS_KEY_ID }}
      OSN_SECRET: ${{ secrets.MW_ACCESS_SECRET }}
      MW_FTP_USER: ${{ secrets.MW_FTP_USER }}
      MW_FTP_URL: ${{ secrets.MW_FTP_URL }}
    permissions:
     contents: write
    container: rqthomas/flare-rocker:4.4
    steps:
      - uses: actions/checkout@v6

      - name: clone lake repository
        uses: actions/checkout@v6
        with:
          repository: ecoforecastVT/YARR-forecast
          token: ${{ secrets.GIT_PAT }}
          path: forecast-code

      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          install.packages("minioclient")
          remotes::install_version("arrow", version = "20.0.0")
          install.packages('RcppRoll')
          install.packages('RCurl')
          install.packages('here')

      - name: Run Inflow Generation
        shell: Rscript {0}
        run: source("forecast-code/workflows/gml_aed_flare_v3/generate_targets_aed.R")
